### ISSUE TITLE
grafana v0.33.0 not show version on --version

### ISSUE THREAD

**Issue by segator** [grafana/agent#3727] opened 2023-04-29 18:26 UTC
this grafana version is broken is not showing build information neither version.

```
grafana-agent --version
agent, version  (branch: , revision: d25614ee52578ac5a0dc0c6d31c45ee97263843a)
  build user:
  build date:
  go version:       go1.20.3
  platform:         linux/amd64
  tags:             netgo,builtinassets,promtail_journal_enabled

``` 

your [grafana-agent ansible collection](https://github.com/grafana/grafana-ansible-collection) fails when reexecute caused because is empty
```
    - name: Gather currently installed grafana-agent version from the host
      ansible.builtin.shell:
        cmd: |
          {{ grafana_agent_install_dir }}/{{ grafana_agent_binary }} --version | \
            head -n 1 | \
            awk '{ print $3; }' | \
            cut -d 'v' -f 2
```

**Comment by rfratto** [comment] 2023-04-29 18:28
Hi, this is a known issue and a patch release will be produced next week :) 

Closing as dupe of #3645.

**Closed by rfratto** 2023-04-29 18:28 UTC
