### ISSUE TITLE
Incorrect flag in integrations-next autoscrape deserializes incorrect parameter without error.

### ISSUE THREAD

**Issue by rgeyer** [grafana/agent#1840] opened 2022-06-29 20:35 UTC
Given the following config file, the agent will run successfully, but will not actually autoscrape the enabled node_exporter integration.

This is because the correct parameter is `enable: true`, but `enabled: true` is allowed during deserialization, effectively failing silently.

gragent-autoscrape-deser.fail.yaml
```
server:
    http_listen_address: 0.0.0.0
    http_listen_port: 8080
integrations:
    metrics:
        autoscrape:
            enable: false
    node_exporter_configs:
        - autoscrape:
            enabled: true
            metrics_instance: default
```

`docker run --rm -it -p 8080:8080 -v $(pwd):/config grafana/agent:v0.25.1 -config.file /config/gragent-autoscrape-deser-fail.yaml -enable-features integrations-next -config.enable-read-api`

In the resulting config (`curl localhost:8080/-/`), note that the node_exporter integration is set to `enable: false`.

The expected behavior is that the invalid parameter `enabled` would cause a deserialization error.

**Comment by tpaschalis** [comment] 2022-07-04 14:23
Thanks for opening this issue! I think there's a couple of issues at play here.

1) The node exporter is a singleton integration. Thus, it should be configured using a `node_exporter` block, and not with an `XXX_configs:` array. This is also _not enforced_ while unmashalling, which leads us to..

2) As you mentioned, the unmarshalling does _not_ end up recognizing incorrect fields. This is likely due to the way that we are shimming configuration of v1 integrations into v2. I haven't done a deep dive of how this works, but the root cause seems to be somewhere around [here](https://github.com/grafana/agent/blob/542a42d2660affa582904ac2bb78e716de46c447/pkg/util/yaml.go#L59-L123), and that we _do_ just ignore unknown fields. 

I agree with your view on the expected behavior, and that maybe we should work towards stricter unmarshalling of configuration for shimmed integrations. If someone wants to take a stab, hopefully the previous link along with [this](https://github.com/grafana/agent/blob/542a42d2660affa582904ac2bb78e716de46c447/pkg/integrations/v2/register.go#L274) are a good starting point to delve into how it all ties together.

**Comment by jcreixell** [comment] 2023-10-30 16:47
@rgeyer thanks for reporting this. Fixing this at this point would be a breaking change, and given that Flow does not have this problem, we will close this for now.

**Closed by jcreixell** 2023-10-30 16:47 UTC
Labels: bug, keepalive, type/infrastructure
