### ISSUE TITLE
Empty YAML server stanza causes debug-level logging

### ISSUE THREAD

**Issue by neomantra** [grafana/agent#2607] opened 2022-12-12 01:37 UTC
If `agent` is configured with an empty `server` stanza in YAML:

```yml
server:
metrics:
...

```

Then `log_level` and `log_format` will lose their defaults and be assigned empty strings, as shown by the `-/config` endpoint:

```yml
server:
  log_level: ""
  log_format: ""
  grpc_tls_config: {
...
```

The [default values are supposed to be](https://grafana.com/docs/agent/latest/configuration/server-config/) `info` and `logfmt`.

For the `log_level`, unfortunately an unknown level is mapped to "all" by the logging library; this generates *significant amounts* of unwanted log output. 
https://github.com/cortexproject/cortex/blob/v1.11.0/pkg/util/log/log.go#L124

Ironically, I triggered this issue as part of upgrading my config from `v0.24`:
```diff
 server:
-  http_listen_address: '{{ ansible_host }}'
-  http_listen_port: 9090
metrics:
``` 

Adding any other entry to the stanza alleviates the issue: 

```yml
server:
  http_tls_config:
```

I stepped through and thought about it for a bit, and I think that in the case of just `server:`, the `config.Config.Server` is getting Golang-default-initialized, which puts empty strings in those fields, whereas in the `server: http_tls_config:` case, it is specifically `config.Config.Server.HTTP.TLSConfig` that is getting default-initialized.  And of course if no `server:` is specified, there is nothing overwritten.

I think the best course of action is to specifically check for default-initialization of those fields, since Golang want `""` and Agent wants `info / logfmt`.   It is unlikely an operator would intentionally make blank and it's invalid anyway.

**Comment by neomantra** [comment] 2022-12-12 17:24
I thought about this further to verify... and just checked that a stanza like this will *not* elicit the issue and `log_level` remains correctly configured:

```
server:
  log_format: "logfmt"
```

It must be that `server:` is specified but nothing else under it is -- and thus uses the `config.Config`'s incorrect default initialization of `config.Config.Server`.

So the logic in the PR is correct relative to this issue.   But... maybe each of `log_level` and `log_format` should be independently checked for `!= ""` to benefit the Agent's operator as  `""` is invalid for both?

**Comment by tpaschalis** [comment] 2022-12-15 18:48
Hey Evan! 👋  Thanks for bringing this to our attention! Incidentally, the cause of this is similar to #2618.

Generally, we have avoided providing meaning to empty YAML blocks like `server:` in our Agent config (in contrast to say, the OpenTelemetry collector configuration which makes heavy use of them).

I think this is the crux of the issue; if the block is missing completely, or defined as empty via `server: {}` instead, then the default values will be applied correctly.

I'm thinking whether we should make an exception to correctly handle _this_ case of an empty block as per your PR, or if we should error out earlier here cc @ptodev @erikbaranowski for some more feedback!

**Comment by neomantra** [comment] 2023-01-11 19:14
To answer my own question on that... `grafana-agent-operator` doesn't take a YAML file, only CLI args, so it's irrelevant.   I did check and the run does correctly reject bad log level values, which as noted above, can cause >debug  logging.

```
> docker run  grafana/agent-operator --log.level ""
invalid value "" for flag -log.level: unrecognized log level ""
...
> docker run  grafana/agent-operator --log.level "xxx"
invalid value "xxx" for flag -log.level: unrecognized log level "xxx"
...
> docker run  grafana/agent-operator --log.level
flag needs an argument: -log.level
```

**Comment by neomantra** [comment] 2023-02-07 13:17
It's been almost two months since I reported this.  I don't care about my specific commit, but while it seems minor, you should take this issue much more seriously.   At minimum, you should include the simplest patch in the next release -- there have been two  releases since I reported.

I will note the key issues for customers:

 * it is unexpected behavior and is easy to trigger with a required config change (see how I triggered it above)
 * it impacts storage and network bandwidth -- a machine gets 10-100x the amount of log output and that output is sent out on LAN or WAN
 * it impacts Grafana/Loki costs, my bill would have been $thousands instead of <$100 if I did not catch it right away
 * it has privacy and security implications -- unexpected >debug level logging is flooding the machine and the network and it's unclear what the debug information might contain

**Comment by rfratto** [comment] 2023-02-07 13:32
Applying a config with `server:` is very unusual, since it explicitly sets the server block to null in YAML parlance. 

I've only ever seen OpenTelemetry Collector assign special meaning to null, which is why we haven't given a lot of priority to this issue; you're the first person we've seen do this for the server block. 

I feel like a documentation warning could be equally as useful here vs a code change.

**Comment by neomantra** [comment] 2023-02-07 14:18
Just because I'm the only person to report it (and dive deep to investigate it), does not mean nobody else is affected by it.    What we are trying to do here is fix it so that it isn't a big, unexpected problem for somebody else.   There is nothing exotic going on here at a user-level.  So sure, having documentation is great, but it will not detect nor fix the underlying issue.

As you note, the issue is precisely that the `server` YAML config is `null` and how Grafana Agent is handling that.

This is due to idiosyncrasies of the YAML parsing library and specifically Golang structure initialization of pseudo-enums.  If this was written in another language/library (not suggesting this at all), the bug wouldn't exist.   One can't expect users to consider that or think "hmmm, was this implemented in Golang and am I allowed to use a `null` YAML block with Grafana configurations or only not in the `server` stanza?"

It is not operator error or configuration error -- YAML allows specifying `null` blocks.  So as Grafana Agent developers, we need to decide "what will we do with a `null` block?"   Currently, the program overwrites valid default configuration with invalid and detrimental configuration.  As a user, I personally would (and did) expect a properly default-initialized config struct.  So as a developer, that's what I implemented.   We could decide to do something else, like fail, but what's happening right now is along the worst outcomes.

I originally contributed a very simple solution: check for the specific bad values.   Then once I understood the codebase better, I used the same techniques to the `server` config struct that the other config structs use to mitigate this exact same `null` YAML issue (using `ApplyDefaults`).      I also added unit tests which clearly demonstrates the issue and provides missing code coverage of the actual startup phase of Grafana Agent.   You can use this to produce exactly the result you want as maintainers;  I suggest default-initialization like the rest of the Agent's config blocks.

**Comment by neomantra** [comment] 2023-02-17 10:49
The rebase I just did is the last one I am going to do for this issue.   

I understand that you have your project priorities, so I'm not personally offended that you are ignoring this issue.  However, I will escalate the issue via other channels as I think it is important for the community.

**Comment by tpaschalis** [comment] 2023-02-21 13:46
Thank you for your report and contribution Evan! If that's okay with you, I'll close this issue as completed.

**Closed by tpaschalis** 2023-02-21 13:46 UTC
Labels: type/core

**Comment by neomantra** [comment] 2023-02-21 13:55
Just a last note that this will be a breaking change for some users, although for the better!
