### ISSUE TITLE
Research on what is needed to embed `node_exporter` 

### ISSUE THREAD

**Issue by gotjosh** [grafana/agent#56] opened 2020-05-05 13:51 UTC
# What we need to do 
As part of agent we want to able to bundle multiple exporters into the agent itself, `node_exporter` is one of them.

 We'd like to understand what is the work to embed it. There are multiple options here which are worth considering:

- We can get the agent to scrape itself with whatever `node_exporter` exposes. This translates to just exposing the exporter metrics into `/metrics` and let the agent scrape the endpoint.

- We can get the contents of the `node_exporter` metrics and ship them through the remote-write storage. 

# Implementation notes
- It is important, that everything goes through the WAL.
- Robert thinks this is just a matter of using a [custom gatherer](https://godoc.org/github.com/prometheus/client_golang/prometheus#Gatherer) and then exposing it.
- A good starting point for understanding what the `node_exporter` is doing is the [main file](https://github.com/prometheus/node_exporter/blob/master/node_exporter.go#L96-L137).
- If we go down the route of agent scraping itself, should we have it on a different `/metrics` endpoint? We believe Prometheus might have increase memory usage if we scrape endpoints with many metrics, plus we'd like to have separate concerns per exporter. 

# Expected output
- We don't necessarily need to write code as an output, writing on next steps should suffice. Specifically, a new **set of issues** on how to tackle it.

**Comment by rfratto** [comment] 2020-05-19 20:22
After some investigation, embedding `node_exporter` isn't the real challenge here; the main challenge is more around how we're going to collect data from an embedded exporter.

As @gotjosh mentioned in the issue, there's two approaches:

1. Expose a custom metrics endpoint for an integration that uses a isolated Prometheus Registerer and has no chance of overlapping with any other Agent metrics. Then the Agent can run an instance that automatically scrapes from these endpoints.
2. Collect metrics in a custom gatherer that bypasses the Prometheus scraper and goes directly into the WAL appender. 

The first approach is nice because integrations aren't treated any differently when it comes to sample collection; they act as any other target. The second code might save more memory by bypassing the scraping code, but I'm nervous about it in general, as I recognize the scraping code is complex and does a lot more than "just call a /metrics endpoint every n seconds." 

For now, I'm partial to the first approach. We can always change this decision down the road, but the first approach is going to be more simple to implement and less error prone as we don't have to try to reproduce every behavior of the Prometheus scrape manager. 

WDYT @gotjosh @hoenn? If we're all on board with this, I'll create issues for building a system to handle integrations and close this issue as completed.

**Comment by rfratto** [comment] 2020-05-20 16:42
After discussion internally, the first approach is clearly preferable, as it is quicker to implement and less risky. We can always implement the second method down the road. 

I'm going to close this issue; this has been effectively split into #83 and #84.

**Closed by rfratto** 2020-05-20 16:42 UTC
