### ISSUE TITLE
grafana-agent-operator volumes not forwarded to DaemonSet

### ISSUE THREAD

**Issue by mar-pan** [grafana/agent#1768] opened 2022-06-01 20:52 UTC
Hello I'was trying to mount volumes to GrafanaAgent CRD to make use of Secrets Store CSI Driver. It seems that currently it's not possible because volumes are not forwarded correctly (only volume mounts are forwarded).  I saw #1524 and its says that it's fixed but I'm using newest version (v0.24.2) and issue persist
`daemonset: DaemonSet.apps \"grafana-agent-logs\" is invalid: [spec.template.spec.containers[0].volumeMounts[6].name: Not found: \"grafana-secret-two\", spec.template.spec.containers[1].volumeMounts[6].name: Not found: \"grafana-secret-two\"]`

**Comment by rfratto** [comment] 2022-06-02 16:27
Hi, thanks for reporting. Can you share your CRDs so we can try to reproduce?

**Comment by mar-pan** [comment] 2022-06-02 20:07
Can I upload it zipped?

**Comment by rfratto** [comment] 2022-06-03 21:46
Sure, whatever works for you :)

**Comment by mar-pan** [comment] 2022-06-06 09:11
[templates.zip](https://github.com/grafana/agent/files/8843234/templates.zip)
find it attached

**Comment by rlankfo** [comment] 2022-06-08 22:45
Hi @mar-pan, I looked into this issue and I could not reproduce in `v0.25.0`.  Could you upgrade to this version? There were some refactorings done to the operator when integrations were introduced in this version around how we generate the `PodTemplateSpec` objects for deployments and daemonsets. I believe these changes make sure the volumes are copied over properly which should resolve your issue.

Please let me know if you run into any issues after upgrading to this version. Thanks 🙏

**Comment by rlankfo** [comment] 2022-06-10 23:17
Closing, feel free to re-open if upgrade to v0.25.0 doesn't solve the problem.

**Closed by rlankfo** 2022-06-10 23:17 UTC
Labels: bug, operator

**Comment by mar-pan** [comment] 2022-06-17 15:43
I cannot download v0.25.0 version is it public?
![image](https://user-images.githubusercontent.com/102954121/174332003-3f21e83b-30de-431c-8fdc-49cf96706993.png)

**Comment by mar-pan** [comment] 2022-06-17 15:48
I upgraded chart to 2.0 but still the highest container i got is 0.24
![image](https://user-images.githubusercontent.com/102954121/174332712-b429f14c-c127-4947-a5c0-fc31551e4810.png)
