### ISSUE TITLE
[bug] Flow stops scraping kubelet metrics correctly after node update

### ISSUE THREAD

**Issue by payparain** [grafana/agent#2640] opened 2022-12-21 03:13 UTC
When the Agent is started in Flow mode on a kubernetes cluster, initially all is fine and metrics are scraped from the kubelet and cAdvisor endpoints as expected using the below configuration:

```
discovery.kubernetes "k8s_node" {
	role = "node"
}

discovery.relabel "configure_kubelet" {
	targets = discovery.kubernetes.k8s_node.targets

	rule {
		replacement  = "kubernetes.default.svc:443"
		target_label = "__address__"
	}

	rule {
		regex         = "(.+)"
		replacement   = "/api/v1/nodes/$1/proxy/metrics"
		source_labels = ["__meta_kubernetes_node_name"]
		target_label  = "__metrics_path__"
	}
}

prometheus.scrape "kubelet_scrape" {
	targets      = discovery.relabel.configure_kubelet.output
	job_name     = "integrations/kubernetes/kubelet"
	scheme       = "https"
	honor_labels = true
	forward_to   = [prometheus.relabel.kubelet_filters.receiver]

	http_client_config {
		bearer_token_file = "/var/run/secrets/kubernetes.io/serviceaccount/token"

		tls_config {
			ca_file              = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
			insecure_skip_verify = false
			server_name          = "kubernetes"
		}
	}
}
```

This allows us to view metrics such as `kubelet_volume_stats_capacity_bytes` and friends on a Prometheus instance that the Agent writes to (either Grafana Cloud or otherwise).  However, during operation, when the Agent encounters multiple consecutive updates to the kubernetes discovery component for the nodes, metrics no longer are accurately scraped (either missing labels, or not scraped at all). This is a graph of what this looks like on Prometheus:
<img width="1495" alt="Screen Shot 2022-12-21 at 1 06 08 pm" src="https://user-images.githubusercontent.com/106503014/208811825-2226ab26-9c5d-4a92-ada8-230aff41bf95.png">

And this is what the Agent logs right at that cutoff point when it stops sending accurate metrics:

```
ts=2022-12-21T03:02:50.641065661Z level=debug msg="handling component with updated state" node_id=discovery.kubernetes.k8s_node
ts=2022-12-21T03:02:50.64109186Z level=info trace_id=9261bea3c087ef8e119b1e503b908949 msg="starting partial graph evaluation"
ts=2022-12-21T03:02:50.642117238Z level=debug component=prometheus.scrape.cadvisor_scrape msg="scrape config was updated"
ts=2022-12-21T03:02:50.64245833Z level=debug component=prometheus.scrape.cadvisor_scrape msg="passed new targets to scrape manager"
ts=2022-12-21T03:02:50.643046417Z level=debug component=prometheus.scrape.kubelet_scrape msg="scrape config was updated"
ts=2022-12-21T03:02:50.643065117Z level=info trace_id=9261bea3c087ef8e119b1e503b908949 msg="finished partial graph evaluation" duration=1.982257ms
ts=2022-12-21T03:02:50.643293912Z level=debug component=prometheus.scrape.kubelet_scrape msg="passed new targets to scrape manager"
ts=2022-12-21T03:02:55.640885487Z level=debug msg="handling component with updated state" node_id=discovery.kubernetes.k8s_node
ts=2022-12-21T03:02:55.640921186Z level=info trace_id=5e7ddd1693ce83c43aa6c36e76024efa msg="starting partial graph evaluation"
ts=2022-12-21T03:02:55.642017562Z level=debug component=prometheus.scrape.cadvisor_scrape msg="scrape config was updated"
ts=2022-12-21T03:02:55.642362055Z level=debug component=prometheus.scrape.cadvisor_scrape msg="passed new targets to scrape manager"
ts=2022-12-21T03:02:55.64300984Z level=debug component=prometheus.scrape.kubelet_scrape msg="scrape config was updated"
ts=2022-12-21T03:02:55.64302954Z level=info trace_id=5e7ddd1693ce83c43aa6c36e76024efa msg="finished partial graph evaluation" duration=2.116054ms
ts=2022-12-21T03:02:55.643278535Z level=debug component=prometheus.scrape.kubelet_scrape msg="passed new targets to scrape manager"
```

This continues on in the logs for a bit before settling down, but the metrics never return to Prometheus, and as a result our dashboards on Grafana. This is happening on 0.29 and 0.30. 

To clarify what I mean by "incomplete" metrics, we still get volume metrics but they're all missing the PVC name; rendering them mostly useless.
<img width="1478" alt="Screen Shot 2022-12-21 at 1 20 43 pm" src="https://user-images.githubusercontent.com/106503014/208813036-7de82645-c338-4498-8e75-b9d73ae906f9.png">

**Comment by rfratto** [comment] 2022-12-21 03:24
👋 I'm on PTO at the moment, but I'm just sitting around waiting to pick someone up at the airport, so I can get started with helping you before handing it off to the rest of the team.

I'd like to track down exactly where the information is starting to get dropped. If you go to the component page in the UI for `prometheus.scrape.kubelet_scrape`, are the targets you're expecting to see appearing in debug info? The debug info will show the actively scraped targets, including when they were last scraped and if scraping failed: 

<img width="833" alt="image" src="https://user-images.githubusercontent.com/630212/208812749-4747a0f6-fff8-4907-8a39-e8a598e71a10.png">

If the targets are appearing there, are actively being scraped, but still aren't showing up, it's happening somewhere in the execution of `prometheus.scrape`. 

If the components _aren't_ appearing there, can you check the rest of the pipeline to see where they disappear? 

* Are the expected targets being exported correctly from `discovery.kubernetes.k8s_node`?
* Does the `targets` argument for `discovery.relabel.configure_kubelet` contain the expected targets with the correct labels?
* Are the targets still displaying in the exports for `discovery.relabel.configure_kubelet`?
* Does the `targets` argument for `prometheus.scrape.kubelet_scrape` contain the expected targets with the correct labels?

Looking through what you've shared so far, nothing stands out yet as being suspicious, but hopefully the team can isolate where this is happening and get a fix going, probably with a patch release if it's a bug. 

To whoever is looking into this: the only thing different here from what we do internally that I can see is setting `honor_labels`. I wonder if that's messing with the cache somehow?

**Comment by payparain** [comment] 2022-12-21 03:33
Hello! The targets from these components (which would be each Node in the cluster), all appear and are reporting `up`, here's an example:

<img width="1044" alt="Screen Shot 2022-12-21 at 1 30 23 pm" src="https://user-images.githubusercontent.com/106503014/208814194-78c143eb-6e1f-4a68-b476-3b937fef76e1.png">

To answer your other questions:

- Yes, all nodes are exported from the discovery component
- Yes, it contains all nodes with the `__metrics_path__` set to the address of the kubelet api
- Yes, all nodes provided as arguments to the `configure_kubelet` component are present in the exported targets with the metrics path updates

**Comment by rfratto** [comment] 2022-12-21 04:11
I think I see a potential issue in the code that could be causing this. 

https://github.com/grafana/agent/blob/d4632459060d157decfb6f7c2f2f84b5acc4e089/component/prometheus/relabel/relabel.go#L176

We're passing the original labels slice directly into `relabel.Process`, where it reuses that slice for processing the relabel rules. The documentation for `relabel.Process` is misleading: it says that it returns a copy _and_ that it may modify the original slice (and modification is definitely possible, after tracing through the code).

All instances of relabel.Process that I could find in Prometheus relabel a _new_ slice (usually from the result of a label builder), so I think we have to make a copy of the labels before relabeling:

```go 
relabelled = relabel.Process(lbls.Copy(), c.mrc...) 
```


I managed to demonstrate the slice problem in a test, shown below:

<details>
<summary>
Reproducing relabel.Process bug
</summary> 

```go
func TestRelabelOverwrite(t *testing.T) {
	start := labels.Labels{
		{Name: "__name__", Value: "up"},
		{Name: "instance", Value: "my-instance"},
		{Name: "job", Value: "original-job"},
	}

	mrc := []*relabel.Config{
		{
			SourceLabels: model.LabelNames{"__name__"},
			Action:       "keep",
			Regex:        relabel.MustNewRegexp("up"),
		},
		{
			TargetLabel: "job",
			Replacement: "integrations/kubernetes/kubelet",
			Action:      "replace",
			Regex:       relabel.MustNewRegexp("(.*)"),
		},
	}

	fmt.Println("INPUT LABELS  ", start.String())

	for i := 0; i < 2; i++ {
		res := relabel.Process(start, mrc...)

		fmt.Println("RELABEL RESULT", res.String())
		fmt.Println("INPUT LABELS  ", start.String())
	}
}
```

```
=== RUN   TestRelabelOverwrite
INPUT LABELS   {__name__="up", instance="my-instance", job="original-job"}
RELABEL RESULT {__name__="up", instance="my-instance", job="integrations/kubernetes/kubelet"}
INPUT LABELS   {__name__="up", instance="my-instance", job="integrations/kubernetes/kubelet"}
RELABEL RESULT {__name__="up", instance="my-instance", job="integrations/kubernetes/kubelet"}
INPUT LABELS   {__name__="up", instance="my-instance", job="integrations/kubernetes/kubelet"}
--- PASS: TestRelabelOverwrite (0.00s)
```

Notice how the job label changes after the first relabel. 
</details>

I haven't fully dug into what impact this issue has on the global ref ID lookup/assignment, but I don't think it explains the original report here, so it may just be an unrelated bug.

**Comment by payparain** [comment] 2022-12-21 04:25
Just a follow up; you mentioned previously you don't use `honor_labels`, so I disabled that but the same behaviour appears: 
<img width="1470" alt="Screen Shot 2022-12-21 at 2 22 06 pm" src="https://user-images.githubusercontent.com/106503014/208820749-9e9d3b42-7648-4d75-8608-4e56f348a4aa.png">

Including the very rapid updating of the discovery component in a short time

**Comment by rfratto** [comment] 2022-12-24 06:55
I think I may have figured this out. I suspect there’s a deadlock in handling staleness markers in prometheus.relabel, which could be triggered by new nodes being discovered. The code tries to grab a write lock to remove an entry from the cache when a read lock is already being held. 

When you’re seeing the missing metrics, is the number of goroutines increasing constantly?

**Comment by rfratto** [comment] 2022-12-24 17:23
I've tried a few things to reproduce this locally in a simpler environment (e.g., no Kubernetes), but haven't had any luck so far. I'll try a real Kubernetes environment next. 

Where did you get the list of relabel rules for Kubelet metrics? Was it from the [Reducing Kubernetes metrics usage](https://grafana.com/docs/grafana-cloud/billing-and-usage/control-prometheus-metrics-usage/usage-reduction-k8s/) page?

**Comment by rfratto** [comment] 2022-12-24 17:25
Also, if you hit the `/-/reload` endpoint of the agent's HTTP server (which causes the entire graph to reevaluate), do the metrics immediately stop appearing?

**Comment by rfratto** [comment] 2022-12-26 18:41
> I see an issue in the code that could be related to this. 

Another issue I'm seeing is that the global ref ID cache doesn't handle hash collisions. That could cause problems with samples getting assigned to another time series, but I don't think hash collisions are what's necessarily happening here. Both the label copying issue and the hash collision issue should still be fixed, though.

**Comment by rfratto** [comment] 2022-12-29 19:31
> I'll try a real Kubernetes environment next.

Unfortunately I'm still not able to reproduce this issue. Here's the config I used: 

<details>
<summary>
Config file
</summary> 

```river 
logging {
	level  = "info"
	format = "logfmt"
}

discovery.kubernetes "nodes" {
	role = "node"
}

discovery.kubernetes "kube_state_metrics" {
	role = "pod"

	namespaces {
		names = ["kube-system"]
	}

	selectors {
		role  = "pod"
		label = "app.kubernetes.io/name=kube-state-metrics"
	}
}

discovery.relabel "kube_state_metrics" {
	targets = discovery.kubernetes.kube_state_metrics.targets

	rule {
		replacement  = "integrations/kubernetes/kube-state-metrics"
		target_label = "job"
	}
}

discovery.relabel "kubelets" {
	targets = discovery.kubernetes.nodes.targets

	rule {
		target_label = "job"
		replacement  = "integrations/kubernetes/kubelet"
	}

	rule {
		target_label = "__scheme__"
		replacement  = "https"
	}

	rule {
		target_label = "__address__"
		replacement  = "kubernetes.default.svc.cluster.local:443"
	}

	rule {
		regex         = "(.+)"
		replacement   = "/api/v1/nodes/${1}/proxy/metrics"
		source_labels = ["__meta_kubernetes_node_name"]
		target_label  = "__metrics_path__"
	}
}

discovery.relabel "cadvisor" {
	targets = discovery.kubernetes.nodes.targets

	rule {
		target_label = "job"
		replacement  = "integrations/kubernetes/cadvisor"
	}

	rule {
		target_label = "__scheme__"
		replacement  = "https"
	}

	rule {
		target_label = "__address__"
		replacement  = "kubernetes.default.svc.cluster.local:443"
	}

	rule {
		regex         = "(.+)"
		replacement   = "/api/v1/nodes/${1}/proxy/metrics/cadvisor"
		source_labels = ["__meta_kubernetes_node_name"]
		target_label  = "__metrics_path__"
	}
}

prometheus.scrape "kubernetes" {
	targets = concat(
		discovery.relabel.cadvisor.output,
		discovery.relabel.kubelets.output,
		discovery.relabel.kube_state_metrics.output,
	)
	forward_to = [prometheus.relabel.kubernetes.receiver]

	http_client_config {
		bearer_token_file = "/var/run/secrets/kubernetes.io/serviceaccount/token"

		tls_config {
			ca_file = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
		}
	}
}

prometheus.relabel "kubernetes" {
	rule {
		source_labels = ["__name__"]
		action        = "keep"
		regex         = "up|kubelet_certificate_manager_client_expiration_renew_errors|kube_replicaset_owner|container_network_receive_packets_dropped_total|container_network_receive_packets_total|go_goroutines|kube_statefulset_status_replicas_updated|kubelet_running_pods|cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests|container_network_transmit_packets_dropped_total|namespace_cpu:kube_pod_container_resource_limits:sum|kube_node_status_condition|kubelet_running_pod_count|container_memory_cache|kube_pod_status_phase|kube_job_status_start_time|container_memory_rss|machine_memory_bytes|kubelet_pleg_relist_duration_seconds_count|storage_operation_errors_total|kube_daemonset_status_desired_number_scheduled|kube_job_status_active|kube_node_status_capacity|node_namespace_pod_container:container_memory_rss|container_memory_working_set_bytes|kube_pod_info|kubelet_runtime_operations_total|kube_statefulset_status_replicas|kubelet_running_container_count|kubelet_node_config_error|process_resident_memory_bytes|kubelet_volume_stats_inodes|kube_daemonset_status_number_misscheduled|kube_job_failed|kube_deployment_metadata_generation|kube_namespace_status_phase|container_fs_writes_bytes_total|kube_resourcequota|kubelet_runtime_operations_errors_total|kube_statefulset_status_observed_generation|kube_node_info|node_namespace_pod_container:container_memory_swap|kube_statefulset_metadata_generation|kube_deployment_status_observed_generation|kube_horizontalpodautoscaler_spec_min_replicas|kubernetes_build_info|kubelet_pleg_relist_duration_seconds_bucket|kube_daemonset_status_current_number_scheduled|node_quantile:kubelet_pleg_relist_duration_seconds:histogram_quantile|container_fs_writes_total|kubelet_cgroup_manager_duration_seconds_count|kube_node_spec_taint|kubelet_server_expiration_renew_errors|container_network_transmit_bytes_total|namespace_memory:kube_pod_container_resource_requests:sum|kube_daemonset_status_number_available|namespace_cpu:kube_pod_container_resource_requests:sum|kube_node_status_allocatable|kubelet_pleg_relist_interval_seconds_bucket|kube_pod_container_resource_limits|kube_statefulset_status_current_revision|kube_horizontalpodautoscaler_status_current_replicas|kubelet_running_containers|namespace_workload_pod|rest_client_requests_total|kube_statefulset_status_replicas_ready|kubelet_certificate_manager_server_ttl_seconds|container_cpu_cfs_periods_total|kubelet_pod_start_duration_seconds_count|kube_deployment_status_replicas_updated|kube_pod_owner|kubelet_pod_start_duration_seconds_bucket|kubelet_pod_worker_duration_seconds_bucket|kubelet_node_name|kubelet_volume_stats_capacity_bytes|kube_statefulset_replicas|node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate|node_namespace_pod_container:container_memory_working_set_bytes|container_network_receive_bytes_total|kubelet_cgroup_manager_duration_seconds_bucket|container_network_transmit_packets_total|container_fs_reads_total|container_cpu_cfs_throttled_periods_total|kubelet_volume_stats_available_bytes|kube_statefulset_status_update_revision|kube_deployment_status_replicas_available|kubelet_certificate_manager_client_ttl_seconds|kubelet_pod_worker_duration_seconds_count|kube_deployment_spec_replicas|container_cpu_usage_seconds_total|cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits|storage_operation_duration_seconds_count|container_fs_reads_bytes_total|kubelet_volume_stats_inodes_used|namespace_memory:kube_pod_container_resource_limits:sum|volume_manager_total_volumes|node_namespace_pod_container:container_memory_cache|kube_pod_container_resource_requests|container_memory_swap|kube_horizontalpodautoscaler_status_desired_replicas|kube_daemonset_status_updated_number_scheduled|cluster:namespace:pod_memory:active:kube_pod_container_resource_limits|process_cpu_seconds_total|cluster:namespace:pod_memory:active:kube_pod_container_resource_requests|namespace_workload_pod:kube_pod_owner:relabel|kube_pod_container_status_waiting_reason|kube_horizontalpodautoscaler_spec_max_replicas|kube_namespace_status_phase|container_cpu_usage_seconds_total|kube_pod_status_phase|kube_pod_start_time|kube_pod_container_status_restarts_total|kube_pod_container_info|kube_pod_container_status_waiting_reason|kube_daemonset.*|kube_replicaset.*|kube_statefulset.*|kube_job.*|kube_node.*|node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate|cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests|namespace_cpu:kube_pod_container_resource_requests:sum"
	}

	forward_to = [prometheus.remote_write.grafanacloud.receiver]
}

prometheus.remote_write "grafanacloud" {
	external_labels = {
		cluster = env("CLUSTER_NAME"),
	}

	wal {
		truncate_frequency = "15m"
	}

	endpoint {
		name = "grafanacloud"
		url  = env("METRICS_URL")

		http_client_config {
			basic_auth {
				username      = env("METRICS_USERNAME")
				password_file = "/etc/secrets/apiToken"
			}
		}
	}
}
```
</details>

This is a little different from the config file you're using, but should still be producing the same metrics.

I have a few more questions:

1. What do you need to do to recover from the issue? Is restarting the agent enough?
2. Are you persisting the WAL between restarts?

**Comment by payparain** [comment] 2023-01-09 05:41
I modified my Flow config to mirror yours (concat the scrapes into one, apply more of the labels (ie fix `__scheme__` to https) and it seems to have resolved the issue. I suspect either; 

- The relabelling rules I had on my individual scrapes may have been impacting the series. The rules were simply:
```
rule {
		source_labels = ["__name__"]
		action        = "keep"
		regex         = "up|...<metric names here>"
	}
rule {
		action       = "replace"
		target_label = "job"
		replacement  = "integrations/kubernetes/cadvisor"
	}
```

Which preserved the job label (whereas the rules in your reply do not), and I suspect that might be a factor

- The minor differences in the approach for relabelling the cadvisor and kubelet targets may have been a factor.
![Screen Shot 2023-01-09 at 3 40 39 pm](https://user-images.githubusercontent.com/106503014/211246844-dbb54024-174c-4999-9322-42dc2fd1a7bb.png)

I can't say for sure; but your changes _have_ fixed the issue. I'll see what I can do re: recreation to diagnose deeper

**Closed** 2023-01-11 00:27 UTC
Labels: bug, type/signals
