### ISSUE TITLE
404 Not Found - apt.grafana.com repo download

### ISSUE THREAD

**Issue by pgodzwa** [grafana/agent#6826] opened 2024-04-05 07:59 UTC
### What's wrong?

When trying to download grafana agent on my Ubuntu machine, following error appears:
`Err:1 https://apt.grafana.com stable/main amd64 grafana-agent amd64 0.40.3-1
  404  Not Found [IP: 151.101.38.217 443]
E: Failed to fetch https://apt.grafana.com/pool/main/g/grafana-agent/grafana-agent-0.40.3-1.amd64.deb  404  Not Found [IP: 151.101.38.217 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?`

### Steps to reproduce

1. Add grafana repo
2. apt update
3. apt install grafana-agent
4. Opening URL manually also shows "Sorry, the requested url was not found" 
https://apt.grafana.com/pool/main/g/grafana-agent/grafana-agent-0.40.3-1.amd64.deb

### System information

Ubuntu 22.04.4

### Software version

latest

**Comment by maloute** [comment] 2024-04-05 08:06
I have the same problem, was also going to open an issue !

**Comment by tpaschalis** [comment] 2024-04-05 08:25
Thanks for the report. I reproduced on my machine, we're looking into it.

**Comment by maloute** [comment] 2024-04-05 10:32
Problem seems to be resolved for me, thanks !

**Comment by Skaronator** [comment] 2024-04-05 10:57
Issue persists for the grafana-agent-flow files:

https://apt.grafana.com/pool/main/g/grafana-agent-flow/grafana-agent-flow-0.40.3-1.amd64.deb

**Comment by julienduchesne** [comment] 2024-04-05 14:48
👋 This should be fixed, can you try again?

**Comment by elasticroentgen** [comment] 2024-04-05 19:21
Works from an Amsterdam host
```
Get:1 https://apt.grafana.com stable/main amd64 grafana-agent-flow amd64 0.40.3-1 [64.4 MB]
Fetched 64.4 MB in 3s (19.9 MB/s)
```

**Comment by tpaschalis** [comment] 2024-04-06 07:30
I'm going to close the issue as resolved. Thanks a lot for the report! 🙌

**Closed by tpaschalis** 2024-04-06 07:30 UTC
Labels: bug
