### ISSUE TITLE
2 out of 76 grafana agents on Windows servers are having issue after upgrading from version 0.34.1 to 0.38.1

### ISSUE THREAD

**Issue by doanbutar** [grafana/agent#6004] opened 2023-12-19 02:19 UTC
### What's wrong?

Upgrading Windows grafana agent from version `0.34.1` to `0.38.1`.
2 out of 76 agents on Windows servers are having an issue scraping the metrics and it's timeout.
One is Windows 2016, and the other is Windows 2019.

Additional context:
The `grafana-agent` sent the metrics to an `prometheus-forwarder` hosted in a AWS ECS then the forwarder sends the data to respective `AMP` workspace.

### Steps to reproduce

1. Install/upgrade agent version 0.38.1

### System information

Windows 2016 and 2019

### Software version

Grafana agent v0.38.1

### Configuration

```text
server:
  log_level: warn
metrics:
  wal_directory: C:\ProgramData\grafana-agent-wal
  global:
    scrape_interval: 1m
    scrape_timeout: 30s
    external_labels:
      application: xxxx
      dashboard: xxxx
      region: xxxx
      site: xxxx
      environmentname: tst
      supportgroup: xxxx
      os: windows
      product: xxxx
    remote_write:
    - url: https://<remote write endpoint>
      basic_auth:
        username: xxxxxxxxx
        password: xxxxxxxxx
  configs:
  - name: integrations
integrations:
  windows_exporter:
    enabled: true
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: windows_(cs_hostname|cs_physical_memory_bytes|cs_logical_processors|system_system_up_time|cpu_time_total|cpu_core_frequency_mhz|cpu_processor_performance_total|cpu_processor_mperf_total|os_info|os_physical_memory_free_bytes|os_virtual_memory_free_bytes|os_virtual_memory_bytes|os_paging_limit_bytes|os_paging_free_bytes|logical_disk_free_bytes|logical_disk_size_bytes|logical_disk_reads_total|logical_disk_writes_total|logical_disk_avg_read_requests_queued|logical_disk_avg_write_requests_queued|net_bytes_sent_total|net_bytes_received_total|net_bytes_total|net_packets_outbound_errors_total|net_packets_received_errors_total|net_current_bandwidth_bytes|net_packets_sent_total|net_packets_received_total|net_packets_total|net_packets_outbound_discarded_total|net_packets_received_discarded_total|net_output_queue_length_packets|exporter_build_info)
        action: keep
```

### Logs

```
level=warn msg="GET /integrations/windows_exporter/metrics 10.6228511s, error: write tcp 127.0.0.1:12345->127.0.0.1:52897: wsasend: An established connection was aborted by the software in your host machine. ws: false; Accept: application/openmetrics-text;version=1.0.0,application/openmetrics-text;version=0.0.1;q=0.75,text/plain;version=0.0.4;q=0.5,/;q=0.1; Accept-Encoding: gzip; User-Agent: GrafanaAgent/v0.34.1; X-Prometheus-Scrape-Timeout-Seconds: 10; "
```

**Comment by ptodev** [comment] 2023-12-19 09:41
Is the problem here with scraping or with remote write?

> 2 out of 76 Windows servers are having an issue to report to the data source.

This line makes is sounds like the problem is with the remote write? However, I think the attached log line is from a failed scrape?

**Comment by doanbutar** [comment] 2023-12-20 00:33
Hello @ptodev sorry for the confusion. The problem is with the scraping. As per the logs, it timeout when scraping the metrics for more than `10s`. I suggested to the customer to increase the `scrape_timeout` to `30s` which is the current config and it works for couple of days until they have seen the issue reoccured even with `30s`.

**Comment by mhixon4479** [comment] 2023-12-21 18:40
See this on a very basic install of 0.38.1 as well across a bunch of windows hosts.

**Comment by ilovelego** [comment] 2023-12-28 04:01
This has been fixed by increased the scape timeout from 10s to 30s: "scrape_timeout: 30s".

However, why this issue only happened on version 0.38.1 but not the previous version ?

**Comment by ilovelego** [comment] 2023-12-28 04:04
With version 0.38.1, it has another issue that some Windows servers are missing of metrics consitently.
Increased the scape timeout from 10s to 30s doesn't fix the issue.

The only workaround is revert to older version but it also has other problem and that was the reason to upgrade.

**Closed** 2024-01-08 15:43 UTC
Labels: bug
