### ISSUE TITLE
The grafana-agent binary supplied in the grafana-agent-0.33.2-1.s390x.deb seems to have been compiled for a PPC64 processor architecture instead of IBM S390x.  

### ISSUE THREAD

**Issue by fionnw29** [grafana/agent#3891] opened 2023-05-16 12:55 UTC
### What's wrong?

The grafana-agent binary supplied in the grafana-agent-0.33.2-1.s390x.deb seems to have been compiled for a PPC64 processor architecture instead of IBM S/390x processor architecture.

After installing the grafana-agent-0.33.2-1.s390x.deb package on my S/390x test system, the grafana-agent failed to start.

Running the "file" command on the binary, installed in "/usr/bin/grafana-agent" shows the following:

`file /usr/bin/grafana-agent
/usr/bin/grafana-agent: ELF 64-bit LSB executable, 64-bit PowerPC or cisco 7500, version 1 (SYSV), dynamically linked, interpreter /lib64/ld64.so.2, BuildID[sha1]=df14874e9df93797e4971564e68699dc775229ed, for GNU/Linux 3.10.0, stripped`

Running the "file" command on the binary "/usr/bin/grafana-agentctl"  (installed in the same package as the grafana-agent) shows the following:

`file /usr/bin/grafana-agentctl 
/usr/bin/grafana-agentctl: ELF 64-bit MSB executable, IBM S/390, version 1 (SYSV), dynamically linked, interpreter /lib/ld64.so.1, BuildID[sha1]=8cff33c9c8607cdccbff5d1638dd6911062b55f9, for GNU/Linux 3.2.0, stripped`

Output of the "dpkg -L grafana-agent" command:

/.
/etc
/etc/default
/etc/default/grafana-agent
/etc/grafana-agent.yaml
/usr
/usr/lib
/usr/lib/systemd
/usr/lib/systemd/system
/usr/lib/systemd/system/grafana-agent.service
/usr/bin
/usr/bin/grafana-agent
/usr/bin/grafana-agentctl
/usr/share
/usr/share/doc
/usr/share/doc/grafana-agent
/usr/share/doc/grafana-agent/changelog.gz

### Steps to reproduce

Installed the downloaded "grafana-agent-0.33.2-1.s390x.deb" package with this command: 

`dpkg -i grafana-agent-0.33.2-s390x.deb`

### System information

Ubuntu Server 20.04 LTS  S/390x

### Software version

Grafana Agent Version 0.33.2

### Configuration

```text
# Sample config for Grafana Agent
# For a full configuration reference, see: https://grafana.com/docs/agent/latest/configuration/.
server:
  log_level: warn

metrics:
  global:
    scrape_interval: 1m
  wal_directory: '/var/lib/grafana-agent'
  configs:
    # Example Prometheus scrape configuration to scrape the agent itself for metrics.
    # This is not needed if the agent integration is enabled.
    # - name: agent
    #   host_filter: false
    #   scrape_configs:
    #     - job_name: agent
    #       static_configs:
    #         - targets: ['127.0.0.1:9090']

integrations:
  agent:
    enabled: true
  node_exporter:
    enabled: true
    include_exporter_metrics: true
    disable_collectors:
      - "mdadm"
```

### Logs

```text
Output from the "systemctl status grafana-agent" command:

systemctl status grafana-agent.service 

● grafana-agent.service - Monitoring system and forwarder
     Loaded: loaded (/lib/systemd/system/grafana-agent.service; disabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2023-05-16 14:11:41 SAST; 2min 44s ago
       Docs: https://grafana.com/docs/agent/latest/
    Process: 963212 ExecStart=/usr/bin/grafana-agent --config.file $CONFIG_FILE $CUSTOM_ARGS (code=exited, status=203/EXEC)
   Main PID: 963212 (code=exited, status=203/EXEC)

May 16 14:11:41 dataw-dev01.bankzerosa.co.za systemd[1]: grafana-agent.service: Main process exited, code=exited, status=203/EXEC
May 16 14:11:41 dataw-dev01.bankzerosa.co.za systemd[1]: grafana-agent.service: Failed with result 'exit-code'.
May 16 14:11:41 dataw-dev01.bankzerosa.co.za systemd[1]: grafana-agent.service: Scheduled restart job, restart counter is at 5.
May 16 14:11:41 dataw-dev01.bankzerosa.co.za systemd[1]: Stopped Monitoring system and forwarder.
May 16 14:11:41 dataw-dev01.bankzerosa.co.za systemd[1]: grafana-agent.service: Start request repeated too quickly.
May 16 14:11:41 dataw-dev01.bankzerosa.co.za systemd[1]: grafana-agent.service: Failed with result 'exit-code'.
May 16 14:11:41 dataw-dev01.bankzerosa.co.za systemd[1]: Failed to start Monitoring system and forwarder.

Output from command: "journalctl -b -u grafana-agent.service"

May 16 14:11:41 dataw-dev01.bankzerosa.co.za systemd[1]: Started Monitoring system and forwarder.
May 16 14:11:41 dataw-dev01.bankzerosa.co.za systemd[963212]: grafana-agent.service: Failed to execute command: Exec format error
May 16 14:11:41 dataw-dev01.bankzerosa.co.za systemd[963212]: grafana-agent.service: Failed at step EXEC spawning /usr/bin/grafana-agent: Exe>
May 16 14:11:41 dataw-dev01.bankzerosa.co.za systemd[1]: grafana-agent.service: Main process exited, code=exited, status=203/EXEC
May 16 14:11:41 dataw-dev01.bankzerosa.co.za systemd[1]: grafana-agent.service: Failed with result 'exit-code'.
May 16 14:11:41 dataw-dev01.bankzerosa.co.za systemd[1]: grafana-agent.service: Scheduled restart job, restart counter is at 5.
May 16 14:11:41 dataw-dev01.bankzerosa.co.za systemd[1]: Stopped Monitoring system and forwarder.
May 16 14:11:41 dataw-dev01.bankzerosa.co.za systemd[1]: grafana-agent.service: Start request repeated too quickly.
May 16 14:11:41 dataw-dev01.bankzerosa.co.za systemd[1]: grafana-agent.service: Failed with result 'exit-code'.
May 16 14:11:41 dataw-dev01.bankzerosa.co.za systemd[1]: Failed to start Monitoring system and forwarder.
```

**Comment by tpaschalis** [comment] 2023-05-16 14:06
Hey there! The issue is fixed in `main`; since a new release is coming in soon, we thought we wouldn't rebuild the previous artifacts, but wait for the next one.

In the meantime, if you want, you can use `make dist-agent-packages-s390x` to rebuild them yourself as a temporary workaround. Would this work for you?

**Comment by fionnw29** [comment] 2023-05-16 14:09
Hi,

Thank you very much for the feedback.

I'm happy to wait for the next release.

Kind Regards,

Fionn.
________________________________

**Comment by tpaschalis** [comment] 2023-05-16 14:13
Thanks Fionn. I'm closing this issue as completed.

**Closed by tpaschalis** 2023-05-16 14:13 UTC
Labels: bug
