### ISSUE TITLE
Wrong result of --version command

### ISSUE THREAD

**Issue by jetexe** [grafana/agent#3730] opened 2023-05-01 09:02 UTC
Hi!
On build `0.33.0` output of `--version` is:

```sh
$ grafana-agent-linux-amd64 --version                                                                                             
agent, version  (branch: , revision: d25614ee52578ac5a0dc0c6d31c45ee97263843a)
  build user:       
  build date:       
  go version:       go1.20.3
  platform:         linux/amd64
  tags:             netgo,builtinassets,promtail_journal_enabled
```

version field is missing

on `0.32.1` was normal:

```sh
$ grafana-agent-linux-amd64 --version
agent, version v0.32.1 (branch: HEAD, revision: f48e41a9)
  build user:       root@ce4f3c31cd6b
  build date:       2023-03-06T19:07:00Z
  go version:       go1.20
  platform:         linux/amd64
```

**Comment by rfratto** [comment] 2023-05-01 13:14
Hi, this is a known issue and a patch release will be produced this week :)

Closing as dupe of https://github.com/grafana/agent/issues/3645.

**Closed by rfratto** 2023-05-01 13:14 UTC
