### ISSUE TITLE
Add support for AIX

### ISSUE THREAD

**Issue by adeverteuil** [grafana/agent#1533] opened 2022-03-29 14:03 UTC
Many financial institutions run their core transactional systems on AIX mainframes.
They also cannot run software compiled by untrusted third parties.

To accomodate financial institution customers:
* Add an integration for https://github.com/thorhs/node_exporter_aix into the Grafana Agent
* Compile and package the Grafana Agent for AIX platforms.

**Comment by rfratto** [comment] 2022-03-29 14:06
This would be really hard for us to do. AIX seems to be its own PowerPC 64-bit OS, and while Go supports it, it will take a lot of effort to get the Agent compiling in a reproducible and automated way that we can use for releases.

**Comment by rfratto** [comment] 2022-03-29 14:07
> Add an integration for https://github.com/thorhs/node_exporter_aix into the Grafana Agent

This is a C++ exporter, which might be possible for us to embed but again, would take a ton of work.

**Comment by adeverteuil** [comment] 2022-03-29 14:56
> Would it be possible for these users to expose their telemetry to Grafana Agent running on a supported platform instead of running it directly on AIX?

Not really, we're looking to expose telemetry about the AIX system itself. Given these are core bank systems, they need any software running on them to be vendor supported, so we can't ask them to run a third party software. Wells Fargo tested the compiled and packaged `node_exporter_aix` by itself, and it worked, but they promptly removed it because running it was against their software security policy. It would have to be either fully code-reviewed and compiled by them, or by us.

I filed the feature request to the Voice of the Customer program, because it is very important for Wells Fargo, and we consistently get this feature request from financial institutions.

More details from our meeting with Wells Fargo here:
https://docs.google.com/document/d/1pIk_skVNAGOfKWOe0iqn9kMzBTlNfZN_mG0QqW14ADU/edit#heading=h.gmfw68yu6chf

**Comment by rfratto** [comment] 2022-06-08 14:46
I'm going to close this for now. It's unlikely we'll add AIX support for Grafana Agent itself, but we're willing to make other AIX-specific tools that an existing Grafana Agent installation can interact with.

**Closed by rfratto** 2022-06-08 14:46 UTC
Labels: keepalive
