### ISSUE TITLE
Support mimir.alerts.kubernetes component

### ISSUE THREAD

**Issue by Paul424** [grafana/agent#6011] opened 2023-12-20 09:07 UTC
### Request

GA has a mimir.rules.kubernetes component which is really helpfull to pickup PrometheusRule resources and push them to a mimir backend (for a given tenant). However rules emit alerts which need to be send to receivers ultimately, for this the multi-tenant-alertmanager needs a tenant specific configuration.

It would be really helpfull if GA can be extended to pickup such configs from a configmap using a selector and push it to the mimir api's (https://grafana.com/docs/mimir/latest/references/architecture/components/alertmanager/).

An alternative (DIY) is to schedule a job that uses mimirtool for this.

### Use case

Configure tenants' AlertManager through GrafanaAgent

**Comment by tpaschalis** [comment] 2024-01-09 13:53
I'm closing this as a duplicate of #2753; there's some conversation around how to implement this, if you're interested in giving it a shot, we'd love to help!

**Closed by tpaschalis** 2024-01-09 13:53 UTC
Labels: enhancement
