### ISSUE TITLE
logs kubernetes service discovery does not log

### ISSUE THREAD

**Issue by dosmanak** [grafana/agent#2945] opened 2023-02-08 08:34 UTC
Hello. I forgot to add ServiceAccount to my Runtime spec in k8s fro grafana-agent.

I tried to configure log scraper using `kubernetes_sd_configs` using image grafana/agent:v0.31.0 .

The agent started succesfuly and did not log any error. I tried to set log_level to debug, but nothing sowed up. Only after I enabled the agent metrics I found there are 403 response codes from kube api.

It seems to me the logging setting is not passed properly to the kubernetes discovery for logs.

https://github.com/grafana/agent/blob/964d8917f0dba273d81b03bbb804086ce90f274a/component/discovery/kubernetes/kubernetes.go#L93

**Comment by rfratto** [comment] 2023-02-08 14:23
Hi, this is a known issue (#2043). From what we can tell, it's not actually the agent code; the Prometheus code upstream also doesn't log if the ServiceAccount is missing or is lacking certain permissions. 

Closing as a dupe of #2043.

**Closed by rfratto** 2023-02-08 14:23 UTC
