### ISSUE TITLE
Fails to start on windows with error `failed to create bookmark using path=C:\\Users\\...\\AppData\\Roaming\\bookmark-application.xml: invalid argument"`

### ISSUE THREAD

**Issue by slim-bean** [grafana/agent#4326] opened 2023-06-30 21:55 UTC
### What's wrong?

Windows service wouldn't start with error:

```
 failed to create bookmark using path=C:\\Users\\...\\AppData\\Roaming\\bookmark-application.xml: invalid argument"
```

I found this file and tried to open it, it tried to open as a binary file with a bunch of NULL characters, I deleted this file and bookmark-system.xml and the agent started correctly (and appears to have recreated these files)

### Steps to reproduce

Don't know what caused it or how it happened, just wanted to share this if someone googles it they will hopefully find the fix that worked for me.

**Comment by rfratto** [comment] 2023-06-30 22:00
Is it possible that your agent crashed recently, leading to data corruption when writing the file?

We could try to make the writes atomic to replace the bookmarks file, that might help with this.

**Comment by mattdurham** [comment] 2023-07-25 14:59
Closing as duplicate of #2545

**Closed by mattdurham** 2023-07-25 14:59 UTC
Labels: bug, type/signals
