### ISSUE TITLE
Grafana Agent v0.24.0 doesn't work with old configuration

### ISSUE THREAD

**Issue by hungran** [grafana/agent#1607] opened 2022-04-13 13:10 UTC
I've used the configuration for getting log Windows system as below with `v.023.0` and it was running as expected
```yaml
server:
  http_listen_port: 12345
metrics:
  wal_directory: C:\ProgramData\grafana-agent-wal
  global:
    scrape_interval: 1m
  configs:
    - name: integrations
integrations:
  windows_exporter:
    enabled: true

logs:
  # Choose a directory to save the last read position of log files at.
  # This directory will be created if it doesn't already exist.
  positions_directory: C:\grafana-agent
  configs:
    - name: windows
      # Loki endpoint to push logs to
      clients:
        - url: https://loki.....
      scrape_configs:
        - job_name: windowslogs
          static_configs:
            - targets: [localhost]
              labels:
                app: appname
                node_name: abc
                __path__: C:\Logs\**\Mobile.log
```
When upgraded to `v0.24.0` with the same as above config the Grafana Agent was not run
Error message:
![image](https://user-images.githubusercontent.com/26101787/163187222-d3df7b69-97e0-4b16-ab8d-db61f5a28550.png)

**Comment by mattdurham** [comment] 2022-04-13 15:08
I cannot reproduce this but did see something similar while testing the release candidate. It went away after trying to restart it a second time. Can you share/look at the windows event log to see if it indicates why it could not start.

**Comment by hungran** [comment] 2022-04-19 04:35
Hi @mattdurham  Not so much info
here is the log I received after changed the configuration file to new one
```html
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
 <System>
  <Provider Name="Service Control Manager" Guid="{555908d1a6d7-4695-8e1e-26931d2012f4}" EventSourceName="Service Control Manager" /> 
  <EventID Qualifiers="49152">7034</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8080000000000000</Keywords> 
  <TimeCreated SystemTime="2022-04-13T07:02:24.496069400Z" /> 
  <EventRecordID>45523</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="956" ThreadID="7948" /> 
  <Channel>System</Channel> 
  <Computer>xxxxxxxx</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data Name="param1">Grafana Agent</Data> 
  <Data Name="param2">1</Data> 
  <Binary>470072006100660061006E00610020004100670065006E0074000000</Binary> 
  </EventData>
  </Event>
```

**Comment by mattdurham** [comment] 2022-04-19 15:02
If you run as a cmd line does it error?

**Comment by hungran** [comment] 2022-04-20 01:39
This was run by PowerShell5.x
I used script (PS + WinRM), not sure with `CMD`
Are there any difference between?

**Comment by mattdurham** [comment] 2022-04-20 13:17
Found the issue and will be fixed in the next release. You need to add a `log_level: info` to the configuration.

**Closed** 2022-04-27 14:14 UTC
Labels: bug, packaging
