### ISSUE TITLE
clustering: refresh peer list on runtime

### ISSUE THREAD

**Issue by tpaschalis** [grafana/agent#4596] opened 2023-07-26 09:16 UTC
### Request

When using clustering, Grafana Agent should periodically re-check the join-addresses and discover-peers fields passed to it to refresh the list of peers, maybe on a configurable interval.

### Use case

This make clustering more robust, allowing it to work for Deployments (where pods don't predictably roll out in sequence).

**Comment by rfratto** [comment] 2023-07-26 11:12
Hi, this is a dupe of #4465; closing as dupe.

**Closed** 2023-07-26 11:12 UTC
Labels: enhancement, type/core
