### ISSUE TITLE
Grafana Agent won't build on Raspbian 12 (bookworm).

### ISSUE THREAD

**Issue by zalintyre** [grafana/agent#5561] opened 2023-10-22 09:32 UTC
### What's wrong?

Grafana Agent won't build on Raspbian 12 (bookworm).

The problem seems to reside in the file `go.mod`, where the Go version has the wrong format. I will create a PR for this.

### Steps to reproduce

* Clone the repository
* Execute `make agent-flow`

### System information

Raspbian 12 (bookworm) @ arm6 32bit

### Software version

v0.37.2

### Configuration

```text
$ cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 12 (bookworm)"
NAME="Raspbian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

```
$ go env
GO111MODULE=''
GOARCH='arm'
GOBIN=''
GOCACHE='/home/pi/.cache/go-build'
GOENV='/home/pi/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/pi/workspace-go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/pi/workspace-go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/opt/go/1.21.1'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/opt/go/1.21.1/pkg/tool/linux_arm'
GOVCS=''
GOVERSION='go1.21.1'
GCCGO='gccgo'
GOARM='6'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -marm -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build2169394670=/tmp/go-build -gno-record-gcc-switches'
```
```


### Logs

```text
go: errors parsing go.mod:
/home/pi/.ansible_build/grafana-agent/go.mod:3: invalid go version '1.21.0': must match format 1.23
gmake: *** [Makefile:207: agent-flow] Error 1", "rc": 2, "stderr": "go: errors parsing go.mod:
/home/pi/.ansible_build/grafana-agent/go.mod:3: invalid go version '1.21.0': must match format 1.23
gmake: *** [Makefile:207: agent-flow] Error 1

go: errors parsing go.mod:
/home/pi/.ansible_build/grafana-agent/go.mod:3: invalid go version '1.21.0': must match format 1.23
gmake: *** [Makefile:207: agent-flow] Error 1
GOOS=linux GOARCH=arm GOARM=6 CGO_ENABLED=1 go build  -ldflags \"-X github.com/grafana/agent/pkg/build.Branch=HEAD -X github.com/grafana/agent/pkg/build.Version=v0.37.2 -X github.com/grafana/agent/pkg/build.Revision=52bc27348 -X github.com/grafana/agent/pkg/build.BuildUser=pi@hallway -X github.com/grafana/agent/pkg/build.BuildDate=2023-10-21T20:34:43Z\" -tags \"\" -o build/grafana-agent-flow ./cmd/grafana-agent-flow", "stdout_lines": ["GOOS=linux GOARCH=arm GOARM=6 CGO_ENABLED=1 go build  -ldflags \"-X github.com/grafana/agent/pkg/build.Branch=HEAD -X github.com/grafana/agent/pkg/build.Version=v0.37.2 -X github.com/grafana/agent/pkg/build.Revision=52bc27348 -X github.com/grafana/agent/pkg/build.BuildUser=pi@hallway -X github.com/grafana/agent/pkg/build.BuildDate=2023-10-21T20:34:43Z\" -tags \"\" -o build/grafana-agent-flow ./cmd/grafana-agent-flow
```
```

**Comment by rfratto** [comment] 2023-10-31 15:51
I'm not able to reproduce this with Go 1.21.3; I'm not sure why it's failing for you but it sounds like there might be something wrong with your Go environment. 

I'm going to close this as can't reproduce, since all of our build systems and local builds seem to work with Go 1.21 with the version specified in the go.mod file.

**Closed by rfratto** 2023-10-31 15:51 UTC
Labels: bug
