### ISSUE TITLE
Getting Error when running in Local

### ISSUE THREAD

**Issue by waytoharish** [grafana/agent#5147] opened 2023-09-11 10:57 UTC
### What's wrong?

Hi,
I am getting following error when running the local setup.

msg="Failed to send batch, retrying" err="Post \"http://localhost:9009/api/prom/push\": dial tcp 127.0.0.1:9009: connect: connection refused"

<img width="851" alt="image" src="https://github.com/grafana/agent/assets/5119613/a5c2fd69-2778-43e8-a490-95c611436eab">

### Steps to reproduce

Checkout the latest code and run the docker-compose up

**Comment by hainenber** [comment] 2023-09-11 14:27
Hi there, I couldn't reproduce your issue using the steps described above. Could you describe the steps in more details?

**Comment by waytoharish** [comment] 2023-09-13 08:07
HI @hainenber ,

I am running the following docker-compose.yaml which is part of the gitrepo in apple M1. Agent is not up and running and I am trying to run it manually .
Once I looked the logs I see following errors-

ts=2023-09-13T08:04:24.618548923Z caller=dedupe.go:112 agent=prometheus instance=9dac8a599fdea3e0cf28c8ae68146bd9 component=remote level=warn remote_name=9dac8a-ca06cf url=http://localhost:9009/api/prom/push msg="Failed to send batch, retrying" err="Post \"http://localhost:9009/api/prom/push\": dial tcp 127.0.0.1:9009: connect: connection refused"
^Cts=2023-09-13T08:05:01.244500718Z caller=gokit.go:72 level=info msg="=== received SIGINT/SIGTERM ===\n*** exiting"
ts=2023-09-13T08:05:01.245167176Z caller=node.go:319 level=info agent=prometheus component=cluster msg="shutting down node"
ts=2023-09-13T08:05:01.245186885Z caller=node.go:345 level=info agent=prometheus component=cluster msg="node shut down"
ts=2023-09-13T08:05:01.245214176Z caller=node.go:169 level=info agent=prometheus component=cluster msg="node run loop exiting"
ts=2023-09-13T08:05:01.245233885Z caller=instance.go:337 level=info agent=prometheus instance=9dac8a599fdea3e0cf28c8ae68146bd9 msg="stopping truncation loop..."
ts=2023-09-13T08:05:01.245250968Z caller=instance.go:359 level=info agent=prometheus instance=9dac8a599fdea3e0cf28c8ae68146bd9 msg="stopping scrape manager..."
ts=2023-09-13T08:05:01.245253593Z caller=config_watcher.go:104 level=info agent=prometheus component=cluster msg="config watcher run loop exiting"
ts=2023-09-13T08:05:01.245265426Z caller=instance.go:333 level=info agent=prometheus instance=9dac8a599fdea3e0cf28c8ae68146bd9 msg="truncation loop stopped"
ts=2023-09-13T08:05:01.245268551Z caller=instance.go:626 level=info agent=prometheus instance=9dac8a599fdea3e0cf28c8ae68146bd9 msg="stopping discovery manager..."
ts=2023-09-13T08:05:01.24527051Z caller=instance.go:623 level=info agent=prometheus instance=9dac8a599fdea3e0cf28c8ae68146bd9 msg="discovery manager stopped"
ts=2023-09-13T08:05:01.245373426Z caller=instance.go:374 level=info agent=prometheus instance=9dac8a599fdea3e0cf28c8ae68146bd9 msg="closing storage..."
ts=2023-09-13T08:05:01.245537468Z caller=instance.go:353 level=info agent=prometheus instance=9dac8a599fdea3e0cf28c8ae68146bd9 msg="scrape manager stopped"
ts=2023-09-13T08:05:01.247097051Z cal

**Comment by tpaschalis** [comment] 2023-09-13 11:27
Can you provide more information?

Which docker-compose are you running; the one present in `example/docker-compose`, the one in `docs/sources/flow/tutorials/assets`, a different one? Can you link to it, or paste its contents after removing any sensitive info? For example the java 'hello-observability' is not something we have on our repo.

Also, how are you launching the docker-compose command?

**Comment by waytoharish** [comment] 2023-09-13 11:30
Using following docker-compose

https://github.com/adamquan/hello-observability/tree/main/local

**Comment by tpaschalis** [comment] 2023-09-13 11:36
I'm not sure what your configuration looks like, but it seems you're trying to reach Prometheus over at `9009` while it exposes port `9090`. 

In any case, this doesn't sound like a bug with the Agent itself, so I think we can close this issue.

If you have any more questions around how to use the Agent, please use our [Community Slack](https://slack.grafana.com/) and the `#agent` channel, or the [Community Forum](https://community.grafana.com/c/support/grafana-agent/69).

**Closed by tpaschalis** 2023-09-13 11:36 UTC
Labels: bug

**Comment by tpaschalis** [comment] 2023-09-13 12:19
@waytoharish as an afterthought, port `9009` is typical for Mimir instead. Were you meaning to use that instead, or are you running multiple docker-compose files in parallel?

**Comment by waytoharish** [comment] 2023-09-13 15:35
I am not using that port anywhere.

`version: "3"
services:

  # The hello-observability application
  hello-observability:
    image: hello-observability
    volumes:
      # Log files. They are all also accessible to the agent container,
      # through docker volume mount
      - ./logs/hello-observability.log:/tmp/hello-observability.log
      - ./logs/access_log.log:/tmp/access_log.log
    environment:
      # Tracing configuration
      JAVA_TOOL_OPTIONS: -javaagent:./opentelemetry-javaagent.jar    
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://tempo:4317
      OTEL_SERVICE_NAME: hello-observability
      OTEL_TRACES_EXPORTER: otlp
    ports:
      - "8080:8080"

  # Our load generator
  load-generator:
    image: curlimages/curl:latest
    volumes:
      - ../hello-observability/load-generator.sh:/tmp/load-generator.sh
    command: /bin/sh -c "/tmp/load-generator.sh"
  
  loki:
    image: grafana/loki:latest
    volumes:
      - ./config/loki-config.yaml:/etc/config/loki.yaml
    entrypoint:
      - /usr/bin/loki
      - -config.file=/etc/config/loki.yaml
    ports:
      - "3100:3100"
     
  tempo:
    image: grafana/tempo:1.5.0
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./config/tempo-local.yaml:/etc/tempo.yaml
      - ./config/tempo-data:/tmp/tempo
    ports:
      - "14268"  # jaeger ingest
      - "3200"   # tempo
      - "4317"  # otlp grpc
      - "4318"  # otlp http
      - "9411"   # zipkin

  prometheus:
    image: prom/prometheus:latest
    command: [
      "--config.file=/etc/prometheus.yaml", 
      "--enable-feature=exemplar-storage",
      "--storage.tsdb.path=/prometheus",
      "--web.console.libraries=/usr/share/prometheus/console_libraries",
      "--web.console.templates=/usr/share/prometheus/consoles",
      "--web.enable-remote-write-receiver"
    ]

    volumes:
      - ./config/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:9.1.0
    volumes:
      # grafana.ini
      # see: https://grafana.com/docs/grafana/latest/setup-grafana/configure-docker/#default-paths
      - ./config/grafana.ini:/etc/grafana/grafana.ini
      # Pre-load the data sources
      - ./config/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      # Pre-load the Hello Observability dashboard
      - ./dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_USERS_DEFAULT_THEME=light
      - GF_FEATURE_TOGGLES_ENABLE=tempoSearch,tempoServiceGraph,tempoApmTable

    ports:
      - "3000:3000"

  agent:
    image: grafana/agent:latest
    volumes:
      # Agent configuration
      - ./config/agent.yaml:/etc/agent-config/agent.yaml
      # Log files
      - ./logs/hello-observability.log:/tmp/hello-observability.log
      - ./logs/access_log.log:/tmp/access_log.log
    entrypoint:
      - /bin/agent
      - -config.file=/etc/agent-config/agent.yaml
      - -metrics.wal-directory=/tmp/agent/wal
      - -enable-features=integrations-next
      - -config.expand-env
      - -config.enable-read-api
    environment:
      HOSTNAME: agent
#      REMOTE_WRITE_HOST: cortex:9009
      LOKI_HOST: loki:3100
      TEMPO_HOST: tempo:3200
    ports:
      - "12345:12345"
    depends_on:
      - loki
      - tempo`
