### ISSUE TITLE
Metadata is not persisting in flow mode

### ISSUE THREAD

**Issue by mattdurham** [grafana/agent#3515] opened 2023-04-11 21:12 UTC
Passing a nil at the end of this ensures that metadata doesn't work.

https://github.com/grafana/agent/blob/main/component/prometheus/remotewrite/remote_write.go#L82

On first pass this seems hard to fix due to the fact there is NOT a tight coupling between remote_write and scrape.

**Comment by rfratto** [comment] 2023-04-11 21:27
Closing as dupe of #1262

**Closed by rfratto** 2023-04-11 21:27 UTC
Labels: type/core, flow
