### ISSUE TITLE
0.40.x: import component reports unknown after soft-reload

### ISSUE THREAD

**Issue by jkroepke** [grafana/agent#6566] opened 2024-02-29 17:41 UTC
### What's wrong?

Hi,

I figure out that that the import components remains `unknown` after do a /-/reload via web.

I have the feeling, that `import.http` components reporting `unknown`, because we have 1 import.http at root scope and 3 import.http at `all.config.this`.

Sadly, the `import.http` component are invisible at UI, this take we around a hour the identify what could be root cause to provide a minimal configuration.

### Steps to reproduce

```
jok@CDT-MB-20200178 cdt-ops-stack % curl -s localhost:12345/metrics | grep running
# HELP agent_component_controller_running_components Total number of running components.
# TYPE agent_component_controller_running_components gauge
agent_component_controller_running_components{controller_id="",health_type="healthy"} 2
jok@CDT-MB-20200178 cdt-ops-stack % curl -s localhost:12345/-/reload              
config reloaded
jok@CDT-MB-20200178 cdt-ops-stack % curl -s localhost:12345/metrics | grep running
# HELP agent_component_controller_running_components Total number of running components.
# TYPE agent_component_controller_running_components gauge
agent_component_controller_running_components{controller_id="",health_type="healthy"} 1
agent_component_controller_running_components{controller_id="",health_type="unknown"} 1
```

### System information

Windows / Linux

### Software version

v0.40.0

### Configuration

```text
import.string "a" {
  content = `declare "b" { export "b" { value = "3" } }`
}

a.b "this" {

}
```

### Logs

```text
ts=2024-02-29T17:37:04.191429Z level=info "boringcrypto enabled"=false
ts=2024-02-29T17:37:04.191455Z level=info msg="running usage stats reporter"
ts=2024-02-29T17:37:04.191458Z level=info msg="starting complete graph evaluation" controller_id="" trace_id=8adb1639947591d08e59d1900f9afa08
ts=2024-02-29T17:37:04.191468Z level=info msg="applying non-TLS config to HTTP server" service=http
ts=2024-02-29T17:37:04.191471Z level=info msg="finished node evaluation" controller_id="" trace_id=8adb1639947591d08e59d1900f9afa08 node_id=http duration=12.5µs
ts=2024-02-29T17:37:04.191475Z level=info msg="finished node evaluation" controller_id="" trace_id=8adb1639947591d08e59d1900f9afa08 node_id=ui duration=250ns
ts=2024-02-29T17:37:04.191478Z level=info msg="finished node evaluation" controller_id="" trace_id=8adb1639947591d08e59d1900f9afa08 node_id=cluster duration=208ns
ts=2024-02-29T17:37:04.19148Z level=info msg="finished node evaluation" controller_id="" trace_id=8adb1639947591d08e59d1900f9afa08 node_id=tracing duration=2.5µs
ts=2024-02-29T17:37:04.191516Z level=info msg="finished node evaluation" controller_id="" trace_id=8adb1639947591d08e59d1900f9afa08 node_id=remotecfg duration=19.75µs
ts=2024-02-29T17:37:04.191519Z level=info msg="finished node evaluation" controller_id="" trace_id=8adb1639947591d08e59d1900f9afa08 node_id=otel duration=208ns
ts=2024-02-29T17:37:04.191523Z level=info msg="finished node evaluation" controller_id="" trace_id=8adb1639947591d08e59d1900f9afa08 node_id=logging duration=94.625µs
ts=2024-02-29T17:37:04.191545Z level=info msg="finished node evaluation" controller_id="" trace_id=8adb1639947591d08e59d1900f9afa08 node_id=import.string.a duration=18.959µs
ts=2024-02-29T17:37:04.191581Z level=info msg="starting complete graph evaluation" controller_id=a.b.this trace_id=7535aaa8a3d7efc24e991be02b8f70cc
ts=2024-02-29T17:37:04.191595Z level=info msg="finished node evaluation" controller_id=a.b.this trace_id=7535aaa8a3d7efc24e991be02b8f70cc node_id=export.b duration=5.833µs
ts=2024-02-29T17:37:04.191601Z level=info msg="finished complete graph evaluation" controller_id=a.b.this trace_id=7535aaa8a3d7efc24e991be02b8f70cc duration=28.875µs
ts=2024-02-29T17:37:04.191738Z level=info msg="finished node evaluation" controller_id="" trace_id=8adb1639947591d08e59d1900f9afa08 node_id=a.b.this duration=187.041µs
ts=2024-02-29T17:37:04.191754Z level=info msg="finished node evaluation" controller_id="" trace_id=8adb1639947591d08e59d1900f9afa08 node_id=labelstore duration=4µs
ts=2024-02-29T17:37:04.191761Z level=info msg="finished complete graph evaluation" controller_id="" trace_id=8adb1639947591d08e59d1900f9afa08 duration=424.166µs
ts=2024-02-29T17:37:04.19204Z level=info msg="scheduling loaded components and services"
ts=2024-02-29T17:37:04.192098Z level=info msg="starting complete graph evaluation" controller_id=a.b.this trace_id=d7df04007f7b974867912defccf329ca
ts=2024-02-29T17:37:04.19211Z level=info msg="finished node evaluation" controller_id=a.b.this trace_id=d7df04007f7b974867912defccf329ca node_id=export.b duration=4µs
ts=2024-02-29T17:37:04.192117Z level=info msg="finished complete graph evaluation" controller_id=a.b.this trace_id=d7df04007f7b974867912defccf329ca duration=48.459µs
ts=2024-02-29T17:37:04.192123Z level=info msg="finished node evaluation" controller_id="" node_id=a.b.this duration=71.916µs
ts=2024-02-29T17:37:04.192154Z level=info msg="scheduling loaded components and services"
ts=2024-02-29T17:37:04.192172Z level=info msg="starting cluster node" peers="" advertise_addr=127.0.0.1:12345
ts=2024-02-29T17:37:04.192286Z level=info msg="peers changed" new_peers=CDT-MB-20200178.fritz.box
ts=2024-02-29T17:37:04.192774Z level=info msg="now listening for http traffic" service=http addr=127.0.0.1:12345
ts=2024-02-29T17:37:16.190953Z level=info msg="reload requested via /-/reload endpoint" service=http
ts=2024-02-29T17:37:16.191205Z level=info msg="starting complete graph evaluation" controller_id="" trace_id=65f9ded278648d30fc2dc17571aa71c5
ts=2024-02-29T17:37:16.191232Z level=info msg="finished node evaluation" controller_id="" trace_id=65f9ded278648d30fc2dc17571aa71c5 node_id=otel duration=4.083µs
ts=2024-02-29T17:37:16.191253Z level=info msg="finished node evaluation" controller_id="" trace_id=65f9ded278648d30fc2dc17571aa71c5 node_id=http duration=8.708µs
ts=2024-02-29T17:37:16.191265Z level=info msg="finished node evaluation" controller_id="" trace_id=65f9ded278648d30fc2dc17571aa71c5 node_id=ui duration=1.875µs
ts=2024-02-29T17:37:16.191277Z level=info msg="finished node evaluation" controller_id="" trace_id=65f9ded278648d30fc2dc17571aa71c5 node_id=cluster duration=3.75µs
ts=2024-02-29T17:37:16.191288Z level=info msg="finished node evaluation" controller_id="" trace_id=65f9ded278648d30fc2dc17571aa71c5 node_id=logging duration=3.458µs
ts=2024-02-29T17:37:16.191336Z level=info msg="finished node evaluation" controller_id="" trace_id=65f9ded278648d30fc2dc17571aa71c5 node_id=import.string.a duration=39µs
ts=2024-02-29T17:37:16.19138Z level=info msg="starting complete graph evaluation" controller_id=a.b.this trace_id=87437568596d7102ae216a96fda87dc4
ts=2024-02-29T17:37:16.19146Z level=info msg="finished node evaluation" controller_id=a.b.this trace_id=87437568596d7102ae216a96fda87dc4 node_id=export.b duration=6.417µs
ts=2024-02-29T17:37:16.191476Z level=info msg="finished complete graph evaluation" controller_id=a.b.this trace_id=87437568596d7102ae216a96fda87dc4 duration=112.417µs
ts=2024-02-29T17:37:16.191491Z level=info msg="finished node evaluation" controller_id="" trace_id=65f9ded278648d30fc2dc17571aa71c5 node_id=a.b.this duration=143.833µs
ts=2024-02-29T17:37:16.191541Z level=info msg="scheduling loaded components and services"
ts=2024-02-29T17:37:16.191744Z level=info msg="finished node evaluation" controller_id="" trace_id=65f9ded278648d30fc2dc17571aa71c5 node_id=remotecfg duration=243.417µs
ts=2024-02-29T17:37:16.191765Z level=info msg="finished node evaluation" controller_id="" trace_id=65f9ded278648d30fc2dc17571aa71c5 node_id=labelstore duration=4.25µs
ts=2024-02-29T17:37:16.19178Z level=info msg="finished node evaluation" controller_id="" trace_id=65f9ded278648d30fc2dc17571aa71c5 node_id=tracing duration=6.625µs
ts=2024-02-29T17:37:16.191788Z level=info msg="finished complete graph evaluation" controller_id="" trace_id=65f9ded278648d30fc2dc17571aa71c5 duration=661.916µs
ts=2024-02-29T17:37:16.191803Z level=info msg="config reloaded" service=http
ts=2024-02-29T17:37:16.191851Z level=info msg="scheduling loaded components and services"
ts=2024-02-29T17:37:16.191972Z level=info msg="starting complete graph evaluation" controller_id=a.b.this trace_id=a63873984d2b42f8ffe4b2192da95728
ts=2024-02-29T17:37:16.192006Z level=info msg="finished node evaluation" controller_id=a.b.this trace_id=a63873984d2b42f8ffe4b2192da95728 node_id=export.b duration=17.708µs
ts=2024-02-29T17:37:16.192024Z level=info msg="finished complete graph evaluation" controller_id=a.b.this trace_id=a63873984d2b42f8ffe4b2192da95728 duration=103.875µs
ts=2024-02-29T17:37:16.192039Z level=info msg="finished node evaluation" controller_id="" node_id=a.b.this duration=160µs
ts=2024-02-29T17:37:16.19205Z level=info msg="scheduling loaded components and services"
```

**Comment by tpaschalis** [comment] 2024-03-04 23:51
cc @wildum in case he's already seen something similar?

**Comment by wildum** [comment] 2024-03-05 09:03
Thanks for reporting the bug, here is what I found out:
There are 4 types of runnable nodes: service, builtin_component, custom_component, import config node
On reload, all nodes from these types are copied from the previous graph instead of being recreated if they have the same ID except the import config node which is recreated every time.
The node scheduler, responsible for running the nodes, checks the new list of runnable nodes vs the one currently running. It stops the nodes that are not in the new list and runs the ones that are not already running. The problem is that it thinks that the import node is already running because it matches the same ID. As a result, it keeps the old import config node running and doesn't run the new import config node. Because the new node is not running, it reports an "unknown health".

The fix for this is to copy the import config node instead of recreating it. I have an outdated PR for this https://github.com/grafana/agent/pull/6288. I thought that it was just an optimization but that's actually super important

**Comment by jkroepke** [comment] 2024-03-05 09:12
Would it be possible to add the import nodes on the UI as well?

**Comment by wildum** [comment] 2024-03-05 09:36
That would require quite some changes in the UI backend. We want to rework it to handle all config nodes (including the import nodes) but we don't have room for it right now. It's quite an important topic so we should take care of it in the next months

**Closed** 2024-03-05 16:22 UTC
Labels: bug
