### ISSUE TITLE
Agent metrics are missing HELP documentation

### ISSUE THREAD

**Issue by samjewell** [grafana/agent#2812] opened 2023-01-24 11:51 UTC
I'm trying to follow the docs here:
https://grafana.com/docs/grafana-cloud/billing-and-usage/control-prometheus-metrics-usage/changing-scrape-interval/#grafana-agent

And see the following example query:
```sql
count_over_time(scrape_samples_scraped[1m])
```

I'm trying to understand what the query is doing, so I open up the Metrics-browser and hover that metric name to try to find the HELP metadata for that metric. But there's none there - it's completely missing:

![image](https://user-images.githubusercontent.com/2903904/214263887-87e63d97-511c-4da8-ada9-8bbadea6d2df.png)

Normally HELP metadata for a metric would look like this:
![image](https://user-images.githubusercontent.com/2903904/214284449-a83dd69d-3fc3-4f14-8b3f-f8f0021b1904.png)

Please can you include this metadata when you ship these metrics, so users can understand what they are? Thanks

**Comment by rfratto** [comment] 2023-01-24 11:52
Hey Sam! This is a known issue: #1262. Closing as a duplicate of #1262.

**Closed by rfratto** 2023-01-24 11:52 UTC

**Comment by samjewell** [comment] 2023-01-24 15:42
Hey @rfratto 

Thanks so much for your speedy response, and sorry for the noise here - it can be hard to figure out/track down the original source of the issue.

But I wanted to share: I found that the Prometheus repo itself exposes this metric, but doesn't ship any metadata for it, so I've opened an issue on that repo instead now:
https://github.com/prometheus/prometheus/issues/11884
