### ISSUE TITLE
grafana-agent with chpst -m crashes: "runtime/cgo: pthread_create failed: Resource temporarily unavailable"

### ISSUE THREAD

**Issue by discordianfish** [grafana/agent#694] opened 2021-06-28 13:35 UTC
When running grafana-agent (version v0.16.1 (branch: HEAD, revision: 4f06d8e)) via chpst to limit memory, it crashes with the following error:

```
runtime/cgo: pthread_create failed: Resource temporarily unavailable
```

strace shows that mmap fails:
```
$ chpst -m 1000000000 strace -f -e mmap ./agent-linux-amd64   --config.file=./config.yml
...
mmap(NULL, 1000005632, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = -1 ENOMEM (Cannot allocate memory)
```

The length of memory mmap tries to allocate is always slightly higher than the limit specified by chpst. I suspect that whatever is causing the mmap call is introspecting the available memory and there is an issue in the calculation.

**Comment by rfratto** [comment] 2021-06-28 13:43
Hi, thanks for reporting. We don't call mmap directly, so we'll have to dig in to find which of our dependencies is doing this. Which features are enabled in your config? (ie, metrics, logging, traces, specific integrations)

**Comment by discordianfish** [comment] 2021-06-28 16:09
agent, node-exporter and prometheus_remote_write. No traces etc. This is even reproducible with just this config:
```
---
server:
  http_listen_port: 9940
  log_level: debug
```

**Comment by discordianfish** [comment] 2021-07-30 09:59
Oh c'mon, I don't want to fight that staleness bot..

**Comment by discordianfish** [comment] 2021-07-30 10:01
To manage expectations: Since we moved already towards using otel-collector because of this issue I don't have the mandate to fix this myself. So if nobody wants to address this, feel free to close it.

**Comment by rfratto** [comment] 2021-07-30 15:35
I'm on vacation until the 9th at the moment, but I don't want this issue closed. This seems like a bug, but I haven't had the time to reproduce myself yet. I'll mark this as keepalive so the staleness bot stays away.

**Comment by rfratto** [comment] 2021-07-30 16:30
I've been able to narrow this down to importing `os/user`. This program:

```go
package main

import _ "os/user"

func main() {
}
```

Will crash through chpst:

```
$ chpst -m 1000000000 ./hello                                                                                                                                                                                                              
runtime/cgo: pthread_create failed: Resource temporarily unavailable
```

Given this seems to be a standard library bug, this is going to be beyond my skills to fix.

**Comment by rfratto** [comment] 2021-07-30 16:47
I mentioned this [upstream](https://github.com/golang/go/issues/24484#issuecomment-890015839). I'll leave this issue open for now. If a future version of Go fixes the issue, we'll update the version of Go we use to build the Agent and close the issue.

**Comment by discordianfish** [comment] 2021-08-02 12:06
Interesting! We're running a bunch of golang services via chpst and never ran into it. Maybe none of these were CGO.
Does grafana build without CGO or are they some hard C dependencies?

**Comment by rfratto** [comment] 2021-08-09 17:41
We need CGO for node_exporter at least, we could probably add something to optionally exclude it as a dependency but haven't put any effort into it yet.

**Comment by rfratto** [comment] 2021-09-29 14:52
We've discussed this and decided ultimately to close this issue. None of us feel qualified to look into this on the Go side, and it doesn't seem like tracking this here holds any value for the project.

**Closed by rfratto** 2021-09-29 14:52 UTC
Labels: bug, keepalive

**Comment by discordianfish** [comment] 2021-10-03 10:49
Sure, personally I don't care much about it. But fwiw, my client opt'ed for otel-collector because of the concern of not being able to limit memory usage of grafana-agent.
